# Generated by Django 5.2.9 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="matricula",
            field=models.CharField(
                blank=True,
                help_text="Identificador único de matrícula",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
