# Generated by Django 5.2.9 on 2025-12-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0002_initial"),
        ("sales", "0002_alter_venta_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citas",
                to="clientes.cliente",
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
