# Generated by Django 5.2.9 on 2025-12-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("referencias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "valor",
                    models.CharField(
                        help_text="Expresión como '0 + 7', '0 + 3', etc.", max_length=50
                    ),
                ),
                (
                    "referencia",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="referencias.referencia",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="referencias.tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
                "ordering": ["nombre"],
            },
        ),
    ]
