# Generated by Django 5.2.9 on 2025-12-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("referencias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "valor",
                    models.IntegerField(
                        choices=[
                            (3, "0 + 3"),
                            (4, "0 + 4"),
                            (5, "0 + 5"),
                            (7, "0 + 7"),
                            (10, "0 + 10"),
                        ],
                        help_text="Selecciona uno de los valores permitidos",
                    ),
                ),
                (
                    "referencia",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="referencias.referencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
                "ordering": ["nombre"],
            },
        ),
    ]
