# Generated by Django 5.2.9 on 2025-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oferta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oferta",
            name="tipo",
        ),
        migrations.AlterField(
            model_name="oferta",
            name="valor",
            field=models.IntegerField(
                choices=[
                    (3, "0 + 3"),
                    (4, "0 + 4"),
                    (5, "0 + 5"),
                    (7, "0 + 7"),
                    (10, "0 + 10"),
                ],
                help_text="Selecciona uno de los valores permitidos",
            ),
        ),
    ]
