# Generated by Django 5.2.9 on 2025-12-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oferta", "0001_initial"),
        ("referencias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="tipo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ofertas",
                to="referencias.tipo",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="referencia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ofertas",
                to="referencias.referencia",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="valor",
            field=models.CharField(
                help_text="Expresión como '0 + 7', '0 + 3', etc.", max_length=50
            ),
        ),
    ]
