# Generated by Django 5.2.9 on 2025-12-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionMantenimientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("dias_festivos", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "año", "mes")},
            },
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
                "ordering": ["-fecha"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "fecha"),
                        name="unique_mantenimiento_usuario_fecha",
                    )
                ],
            },
        ),
    ]
