# Generated by Django 5.2.9 on 2025-12-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mantenimientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "ganancia_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Producción",
                "verbose_name_plural": "Producciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "año", "mes"), name="uq_usuario_mes"
                    )
                ],
            },
        ),
    ]
