# Generated by Django 5.2.9 on 2025-12-13 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mantenimientos", "0002_mantenimiento_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionMantenimientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("dias_festivos", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="mantenimiento",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="mantenimiento",
            constraint=models.UniqueConstraint(
                fields=("usuario", "fecha"), name="unique_mantenimiento_usuario_fecha"
            ),
        ),
        migrations.AddField(
            model_name="configuracionmantenimientos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="mantenimiento",
            name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="configuracionmantenimientos",
            unique_together={("usuario", "año", "mes")},
        ),
    ]
