# Generated by Django 5.2.9 on 2025-12-07 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="elemento",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elementos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="elemento",
            name="estado",
            field=models.CharField(
                choices=[("BUENO", "Bueno"), ("DEFECTUOSO", "Defectuoso")],
                max_length=20,
            ),
        ),
    ]
