# Generated by Django 5.2.9 on 2025-12-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
            },
        ),
        migrations.CreateModel(
            name="Referencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "valor",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (3, "0 + 3"),
                            (4, "0 + 4"),
                            (5, "0 + 5"),
                            (7, "0 + 7"),
                            (10, "0 + 10"),
                        ],
                        help_text="Valor asociado a la referencia",
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="referencias.tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referencia",
                "verbose_name_plural": "Referencias",
                "ordering": ["nombre"],
            },
        ),
    ]
