# Generated by Django 5.2.9 on 2025-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referencia",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Referencia",
                "verbose_name_plural": "Referencias",
            },
        ),
        migrations.AddField(
            model_name="referencia",
            name="ganancia",
            field=models.IntegerField(
                blank=True,
                help_text="Ganancia del técnico por cada referencia vendida",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referencia",
            name="valor",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (3, "0 + 3"),
                    (4, "0 + 4"),
                    (5, "0 + 5"),
                    (7, "0 + 7"),
                    (10, "0 + 10"),
                ],
                help_text="Valor asociado a la referencia",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tipo",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
