# Generated by Django 5.2.9 on 2025-12-14 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referencias", "0002_alter_referencia_options_referencia_ganancia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencia",
            name="ganancia",
        ),
    ]
