# Generated by Django 5.2.9 on 2025-12-09 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cita",
            name="direccion",
        ),
    ]
