# Generated by Django 5.2.9 on 2025-12-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="numero_instalacion",
            field=models.IntegerField(default=0),
        ),
    ]
