# Generated by Django 5.2.9 on 2025-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0003_cita_numero_instalacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cita",
            name="venta",
        ),
        migrations.AlterField(
            model_name="cita",
            name="recordatorio",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
