# Generated by Django 5.2.9 on 2025-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0004_remove_cita_venta_alter_cita_recordatorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("pendiente", "Pendiente"), ("completada", "Completada")],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
