# Generated by Django 5.2.9 on 2025-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0005_alter_cita_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
