# Generated by Django 5.2.9 on 2025-12-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0006_cita_observaciones"),
        ("oferta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cita",
            name="oferta",
        ),
        migrations.CreateModel(
            name="CitaOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cita_ofertas",
                        to="citas.cita",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oferta.oferta"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cita",
            name="ofertas",
            field=models.ManyToManyField(
                related_name="citas", through="citas.CitaOferta", to="oferta.oferta"
            ),
        ),
    ]
