# Generated by Django 5.2.9 on 2025-12-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_principal",
                to="locations.address",
            ),
        ),
    ]
