# Generated by Django 5.2.9 on 2025-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
