# Generated by Django 5.2.9 on 2025-12-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_alter_cliente_direccion"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direcciones",
                to="clientes.cliente",
            ),
        ),
    ]
