# Generated by Django 5.2.9 on 2025-12-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_address_cliente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
