# Generated by Django 5.2.9 on 2025-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_address_principal_alter_address_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
