# Generated by Django 5.2.9 on 2025-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="instalacion",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="mantenimiento",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="precio",
        ),
    ]
