# Generated by Django 5.2.9 on 2025-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="mantenimiento_numero",
            field=models.IntegerField(
                blank=True,
                help_text="Número de mantenimiento asociado (opcional)",
                null=True,
            ),
        ),
    ]
