# Generated by Django 5.2.9 on 2025-12-07 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referencias", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="referencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="referencias.referencia",
            ),
        ),
    ]
