# Generated by Django 5.2.9 on 2025-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_venta_mantenimiento_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="ppa",
            field=models.BooleanField(
                default=False, help_text="Marcar si la venta ha convertido PPA"
            ),
        ),
    ]
