# Generated by Django 5.2.9 on 2025-12-18 20:36

import django.db.models.deletion
from django.db import migrations, models


def migrate_ofertas(apps, schema_editor):
    Venta = apps.get_model("sales", "Venta")
    Oferta = apps.get_model("oferta", "Oferta")
    VentaOferta = apps.get_model("sales", "VentaOferta")

    # Copiamos datos antiguos de Venta.oferta y Venta.cantidad a la nueva tabla intermedia
    for venta in Venta.objects.all():
        # los modelos antiguos tenían 'oferta_id' y 'cantidad'
        if hasattr(venta, "oferta_id") and venta.oferta_id:
            try:
                VentaOferta.objects.create(
                    venta=venta,
                    oferta_id=venta.oferta_id,
                    cantidad=getattr(venta, "cantidad", 1),
                )
            except Exception as e:
                print(f"Error migrando venta {venta.id}: {e}")


def reverse_migrate(apps, schema_editor):
    # No revertimos porque los campos antiguos ya no existen
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("oferta", "0001_initial"),
        ("sales", "0003_venta_ppa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="oferta",
        ),
        migrations.CreateModel(
            name="VentaOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oferta.oferta"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venta_ofertas",
                        to="sales.venta",
                    ),
                ),
            ],
            options={
                "unique_together": {("venta", "oferta")},
            },
        ),
        migrations.AddField(
            model_name="venta",
            name="ofertas",
            field=models.ManyToManyField(
                related_name="ventas", through="sales.VentaOferta", to="oferta.oferta"
            ),
        ),
        migrations.RunPython(migrate_ofertas, reverse_migrate),
    ]
