# Generated by Django 5.2.9 on 2025-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_auto_20251218_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="instalacion_numero",
            field=models.IntegerField(
                blank=True,
                help_text="Número de instalacion asociado (opcional)",
                null=True,
            ),
        ),
    ]
